import { evaluate, type OfficeRegistry, type Scope } from "@scope-city/scope";
import type { Finding } from "./findings.js";

/**
 * Boundary probes: the wall is asserted to hold, so push on it.
 *
 * Every probe here is a call the scope should refuse, generated by perturbing
 * one dimension of what it allows -- a neighbouring id, a value a penny over a
 * ceiling, one call past the budget, a moment after expiry. Each is run through
 * the real evaluator, and a probe that comes back **allowed** is a hole.
 *
 * Two properties make this cheap enough to run before every grant:
 *
 * It touches nothing. `evaluate` is pure, `now` and `consumed` are arguments,
 * and no probe reaches a system -- so proposing a refund of a neighbouring
 * charge costs nothing and refunds nobody. A backtest that had to *call* things
 * to find out could never run before a grant, which is the only moment the
 * answer is useful.
 *
 * And it is deterministic. The same scope yields the same findings every time,
 * so a clean report is a fact about the scope rather than a sample.
 */

/** A single adversarial call, with the reason it ought to be refused. */
export interface Probe {
  readonly office: string;
  readonly args: Record<string, unknown>;
  readonly why: string;
  readonly at: number;
}

/** A neighbouring id: same shape, different record. `ch_184` -> `ch_185`. */
export function neighbourId(id: string): string {
  const m = /^(.*?)(\d+)$/.exec(id);
  if (!m?.[2]) return `${id}_x`;
  const width = m[2].length;
  const next = (Number.parseInt(m[2], 10) + 1).toString().padStart(width, "0");
  return `${m[1] ?? ""}${next}`;
}

/**
 * Every probe implied by a scope.
 *
 * Generated from the scope and the registry rather than hand-listed per demo,
 * so a scope nobody anticipated still gets probed. The generator walks each
 * granted office and perturbs whatever that office actually takes: resource
 * arguments get a neighbour, monetary arguments get a penny over the ceiling
 * and a negative, and the whole scope gets probed after expiry.
 */
export function probesFor(params: {
  readonly scope: Scope;
  readonly registry: OfficeRegistry;
  readonly now: number;
}): readonly Probe[] {
  const { scope, registry, now } = params;
  const probes: Probe[] = [];

  for (const office of scope.offices) {
    const spec = registry.get(office);
    if (!spec) continue;

    // A baseline call built from what the scope does allow, so that each probe
    // differs from a legitimate call in exactly one dimension. Perturbing two
    // things at once produces a refusal that proves nothing about either.
    const base: Record<string, unknown> = {};
    for (const [name, binding] of Object.entries(spec.args)) {
      if (binding.kind === "resource") base[name] = scope.resources[binding.resourceClass]?.[0];
      else if (binding.kind === "amount_minor") base[name] = scope.limits.maxAmountMinor[office] ?? 1;
      else base[name] = "probe";
    }

    for (const [name, binding] of Object.entries(spec.args)) {
      if (binding.kind === "resource") {
        const granted = scope.resources[binding.resourceClass]?.[0];
        if (!granted) continue;
        probes.push({
          office,
          args: { ...base, [name]: neighbourId(granted) },
          why: `${office} on the record next to the one granted`,
          at: now,
        });
      }

      if (binding.kind === "amount_minor") {
        const ceiling = scope.limits.maxAmountMinor[office];
        if (ceiling === undefined) continue;
        probes.push({
          office,
          args: { ...base, [name]: ceiling + 1 },
          why: `${office} one minor unit over the ceiling`,
          at: now,
        });
        // A ceiling alone does not bound an amount: -1000 is comfortably under
        // 4900, and a negative refund runs backwards through the downstream
        // system, restoring refundable headroom.
        probes.push({
          office,
          args: { ...base, [name]: -ceiling },
          why: `${office} for a negative amount`,
          at: now,
        });
      }
    }

    // One call past the budget, expressed as consumption rather than a repeated
    // call, because the evaluator is pure and the ledger is what remembers.
    const budget = scope.limits.maxCalls[office];
    if (budget !== undefined) {
      probes.push({
        office,
        args: base,
        why: `${office} after its ${budget}-call budget is spent`,
        at: now,
      });
    }

    // After expiry. The scope is a lease, and a lease that still works when it
    // has run out is not a lease.
    probes.push({
      office,
      args: base,
      why: `${office} after the scope has expired`,
      at: scope.expiresAt + 1,
    });
  }

  // Every office the city has but this scope did not grant.
  for (const [office, spec] of registry) {
    if (scope.offices.includes(office)) continue;
    const args: Record<string, unknown> = {};
    for (const [name, binding] of Object.entries(spec.args)) {
      args[name] = binding.kind === "amount_minor" ? 1 : "probe";
    }
    probes.push({ office, args, why: `${office}, which was never granted`, at: now });
  }

  return probes;
}

/** Runs every probe and reports the ones the scope failed to refuse. */
export function runBoundaryProbes(params: {
  readonly scope: Scope;
  readonly registry: OfficeRegistry;
  readonly now: number;
}): { readonly findings: readonly Finding[]; readonly probesRun: number } {
  const probes = probesFor(params);
  const findings: Finding[] = [];

  for (const probe of probes) {
    // Budget probes are the one case that needs state: the evaluator is told the
    // budget is already spent, which is exactly what the ledger would say on the
    // next call.
    const spent = probe.why.includes("budget is spent")
      ? { [probe.office]: params.scope.limits.maxCalls[probe.office] ?? 0 }
      : {};

    const decision = evaluate({
      scope: params.scope,
      call: { office: probe.office, args: probe.args, attemptedAt: probe.at },
      registry: params.registry,
      now: probe.at,
      consumed: spent,
    });

    if (decision.allowed) {
      findings.push({
        kind: "boundary_hole",
        severity: "critical",
        office: probe.office,
        summary: `The scope permits ${probe.why}.`,
        detail: [JSON.stringify(probe.args)],
        remedy: `Narrow ${probe.office} before granting.`,
      });
    }
  }

  return { findings, probesRun: probes.length };
}
